[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fake-useragent-fixed"
version = "0.0.0"
description = "Fixed version for Issue #446 of fake-useragent"
readme = "README.md"
requires-python = ">=3.8"

[tool.pytest]
addopts = "-q"
